### ISSUE TITLE
Q: why is py-lapsolver so much faster than its counterparts like scipy.optimize.linear_sum_assignment or sklearn.utils.linear_assignment_?

### ISSUE THREAD

**Issue by guoyangqin** [cheind/py-lapsolver#6]
Thanks for this package, it saves me a huge amount of time.

Just wondering why is it so much faster? Is it because of a better algorithm or being based on C. If latter, why didn't scipy.optimize.linear_sum_assignment or sklearn.utils.linear_assignment_ develop based on C? Thanks.

**Comment by cheind** [comment]
Hard to tell, as I'm not familiar with the details of the scipy implementation. The problem is O(n^x) where x in {3,4} depending on the implementation (see [1]).  A genuine C implementation might cure any overhead that stems from looping in interpreted languages.

[1] http://www.assignmentproblems.com/doc/LSAPIntroduction.pdf
